name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push Docker Image to AWS ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS ECR credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t myapp .

      - name: Tag Docker image
        run: |
          docker tag dharani12345/myapp:1

      - name: Push Docker image to Amazon ECR
        run: |
          docker push dharani12345/myapp:1
